
name: Build Project

on: workflow_dispatch

env:
    outputTarfile: /tmp/terminal_radio.tar.xz
    goDownloadLink: https://go.dev/dl/go1.25.1.linux-amd64.tar.gz
    goDownloadFilename: /tmp/go1.25.1.linux-amd64.tar.gz

jobs:
    build-project:
        runs-on: ubuntu-latest

        steps:
          - name: Step 1 - Checkout Repository
            uses: actions/checkout@v4

          - name: Step 2 - Install Build Dependencies
            run: |
                apt update
                apt install -y sqlite3
                wget ${{env.goDownloadLink}} -O ${{env.goDownloadFilename}}
                tar -xzf ${{env.goDownloadFilename}} -C /usr/local

          - name: Step 3 - Create Directories
            run: mkdir logs/

          - name: Step 4 - Create Database
            run: sqlite3 resource/radio_sources.sqlite < resource/schema.sql

          - name: Step 5 - Build Project
            run: |
              export PATH=$PATH:/usr/local/go/bin
              go build -o terminal_radio ./cmd/terminal_radio/main.go

          - name: Step 6 - Compress Project
            run: tar --exclude tests/ -czf ${{env.outputTarfile}} .

          - name: Step 7 - Create Artifact
            uses: actions/upload-artifact@v4.6.2
            with:
                name: archiveFolder
                path: ${{env.outputTarfile}}